[plugin]
package = "eventyay-stripe"
modules = [ "eventyay_stripe" ]
marketplace_name = "stripe"
pypi = true
repository_servers = { origin = "github.com" }
tag_targets = [ "origin" ]
branch_targets = [ "origin/master" ]
